name: DEPLOY TO STAGING

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-16.04
    name: Node
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Installing project dependencies
      - run: npm install
      - name: Building the project
      - run: npm run build     
